jobs:
  - name: script-1
    type: runSh
    steps:
      - IN: sample-script-2
      - IN: trigger-1
      - TASK:
        - script: ls
        - script: echo "ran ls now"
        - script: pwd
    on_success:
      - ohce
